sudo: false
language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=flake8
    - python: "2.7"
      env: TOXENV=coverage
      install: pip install tox coveralls
      after_success: coveralls
    - python: "2.7"
      env: TOXENV=py27-django18-sqlite
    - python: "2.7"
      env: TOXENV=py27-django18-postgres
    - python: "2.7"
      env: TOXENV=py27-django19-sqlite
    - python: "2.7"
      env: TOXENV=py27-django19-postgres
    - python: "3.4"
      env: TOXENV=py34-django18-sqlite
    - python: "3.4"
      env: TOXENV=py34-django18-postgres
    - python: "3.4"
      env: TOXENV=py34-django19-sqlite
    - python: "3.4"
      env: TOXENV=py34-django19-postgres
    - python: "3.5"
      env: TOXENV=py35-django18-sqlite
    - python: "3.5"
      env: TOXENV=py35-django18-postgres
    - python: "3.5"
      env: TOXENV=py35-django19-sqlite
    - python: "3.5"
      env: TOXENV=py35-django19-postgres
install:
  - pip install tox
before_script:
  - psql -c 'create database timezone_field_tests;' -U postgres
script:
  - tox
